name: Pull Request checks
on:
  pull_request: ~
  workflow_dispatch: ~

jobs:
  check_env_vars:
    name: Check all defined environment variables are documented
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run ci/env_vars_check.py
        run: |
          python3 ci/env_vars_check.py

  test_docker_archs:
    name: Test Docker images on all architectures
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm/v7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            -t test \
            --file Dockerfile \
            .
      - name: Run Docker image
        run: |
          docker run \
            --rm \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            test
        # Bot inside will fail because environment variables are not set
