name: Pull Request checks
on:
  pull_request: ~
  workflow_dispatch: ~

jobs:
  config_validation:
    name: Config Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r ci/requirements.txt
      - name: Validate Config
        run: python ci/validate_example_config.py .schema/config_v2.schema.json tauticord.yaml.example

