name: Copy Unraid Community Applications template(s) to templates repository

on:
  release:
    types: [ created ]
  workflow_dispatch: ~

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Establish variables
        id: vars
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=today::$(date +'%Y-%m-%d')

      - name: Prepare git environment
        run: |
          git config --global user.name "nwithan8"
          git config --global user.email "nwithan8@users.noreply.github.com"

      - name: Clone unraid_templates
        env:
          GITHUB_TOKEN: ${{ secrets.PR_OPEN_GITHUB_TOKEN }}
        run: |
          gh repo clone nwithan8/unraid_templates ../unraid_templates

      - name: Copy template(s) to unraid_templates
        run: |
          cp ../tauticord/templates/* ../unraid_templates/templates/
          cd ../unraid_templates
          git add .
          git commit -m "Update Tauticord template for version ${{ steps.vars.outputs.version }} (${{ steps.vars.outputs.today }})"

      - name: Open PR to unraid_templates
        env:
          GITHUB_TOKEN: ${{ secrets.PR_OPEN_GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update Tauticord template for version ${{ steps.vars.outputs.version }} (${{ steps.vars.outputs.today }})" --body "This PR was automatically opened by the \`upload_unraid_template.yml\` workflow." --assignee @nwithan8
